export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";

export const GET_ALL_COMMENTS_LOADING = "GET_ALL_COMMENTS_LOADING";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_ERROR = "GET_ALL_COMMENTS_ERROR";
